sudo: true
dist: bionic

language: generic

services:
  - xvfb

cache:
  directories:
    - $HOME/.stack
    - .stack-work
    - back/.stack-work
  timeout: 1000

jobs:
  include:
    - stage: "Build the backend"
      before_script:
        - sudo apt-get install -y libgmp-dev
        - curl -sSL https://get.haskellstack.org/ | sh
        # travis_retry works around https://github.com/commercialhaskell/stack/issues/4888
        - travis_retry stack setup
      script:
        # Build
        - stack --no-terminal build --test --no-run-tests --dependencies-only
        - stack --no-terminal build --test --no-run-tests
